"use client";

import { useState } from "react";
import CameraDemo from "../src/CameraDemo";

export default function Home() {
  const [demoOpen, setDemoOpen] = useState(false);
  return <main>
    <nav className="nav"><div className="brand"><span className="brand-icon">♥</span><span>PulseWindow</span></div><a href="#how">How it works</a><a href="#care">For care teams</a><a href="mailto:admin@pulsewindow.me">Contact</a><button className="nav-cta" onClick={() => setDemoOpen(true)}>See the concept</button></nav>
    <section className="hero"><div className="hero-copy"><p className="eyebrow">REMOTE HEALTH SUPPORT</p><h1>A clearer window into how a patient is doing.</h1><p className="lead">PulseWindow is a research prototype that helps patients capture pulse and breathing-rate trends from a phone or laptop camera, ready to discuss during a remote consultation.</p><div className="hero-actions"><button className="primary" onClick={() => setDemoOpen(true)}>Explore the prototype <span>→</span></button><a className="text-link" href="#how">Learn how it works <span>↓</span></a></div><p className="note">Wellness prototype only. It does not diagnose, prescribe, or replace clinical equipment.</p></div><div className="hero-card"><div className="card-top"><span className="live-dot"></span><span>Illustrative patient check-in</span><span className="lock">⌁ Private by design</span></div><div className="reading"><div><small>Latest pulse</small><strong>74 <em>BPM</em></strong><span className="trend">↗ Steady over this check-in</span></div><div className="pulse-ring"><span>♥</span></div></div><div className="mini-chart"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><div className="card-foot"><span>Camera signal: acceptable</span><span>08:42 AM</span></div></div></section>
    <section className="trust"><p>Designed for the moments between appointments</p><div><span>Patient-friendly</span><span>Medication-aware</span><span>Doctor-ready summaries</span></div></section>
    <section id="how" className="section"><div className="section-heading"><p className="eyebrow">THE IDEA</p><h2>From a quick check-in to a useful conversation.</h2><p>PulseWindow turns small colour changes and gentle movement into a simple trend that a patient can share with their healthcare team.</p></div><div className="steps"><article><b>01</b><h3>Look at the camera</h3><p>The app guides the patient into a steady position and checks signal quality before recording.</p></article><article><b>02</b><h3>Capture a short reading</h3><p>Remote photoplethysmography, or rPPG, estimates pulse from subtle changes in reflected facial light.</p></article><article><b>03</b><h3>Share the context</h3><p>Medication timing, symptoms, and trends can be reviewed together during a telehealth appointment.</p></article></div></section>
    <section id="care" className="care-section"><div><p className="eyebrow">BUILT AROUND CARE</p><h2>Useful context, not another number.</h2><p>Patients can see when a check is due, record how they feel, and keep their information organised. Clinicians can receive a concise timeline instead of disconnected readings.</p><button className="secondary" onClick={() => setDemoOpen(true)}>View the care-team concept <span>→</span></button></div><div className="care-list"><div><span>01</span><strong>Medication-aware check-ins</strong><p>Prompts can be set by a clinician around an existing care plan.</p></div><div><span>02</span><strong>Simple trend history</strong><p>Pulse and experimental breathing-rate estimates sit beside the date and context.</p></div><div><span>03</span><strong>Exportable summaries</strong><p>A readable report can support, never replace, professional judgement.</p></div></div></section>
    <section className="closing"><p className="eyebrow">A RESEARCH-LED CONCEPT</p><h2>Better remote conversations start with better context.</h2><p>PulseWindow is being developed with pharmacists, patients, and healthcare collaborators to explore what a calm, accessible check-in could look like.</p><button className="primary" onClick={() => setDemoOpen(true)}>See the concept <span>→</span></button></section>
    <footer><div className="brand"><span className="brand-icon">♥</span><span>PulseWindow</span></div><span>Remote monitoring concept · Built for discussion</span><a href="mailto:admin@pulsewindow.me">admin@pulsewindow.me</a><span>© 2026 PulseWindow</span></footer>
    {demoOpen && <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="PulseWindow camera prototype"><div className="modal demo-modal"><button className="close" onClick={() => setDemoOpen(false)} aria-label="Close">×</button><p className="eyebrow">CAMERA PROTOTYPE</p><h2>Try a live check-in.</h2><p>Allow camera access to see the prototype read a green-channel signal locally in your browser.</p><CameraDemo /><button className="modal-back" onClick={() => setDemoOpen(false)}>Back to overview</button></div></div>}
  </main>;
}
