"use client";

import { useState } from "react";
import CameraDemo from "../src/CameraDemo";
import { SiteFooter, SiteNav } from "./SiteChrome";

export default function Home() {
  const [demoOpen, setDemoOpen] = useState(false);
  return <main>
    <SiteNav onDemo={() => setDemoOpen(true)} />
    <section className="hero"><div className="hero-copy"><p className="eyebrow">REMOTE HEALTH SUPPORT</p><h1>A clearer window into how a patient is doing.</h1><p className="lead">PulseWindow is a research prototype that helps patients capture pulse and breathing-rate trends from a phone or laptop camera, ready to discuss during a remote consultation.</p><div className="hero-actions"><button className="primary" onClick={() => setDemoOpen(true)}>Explore the prototype <span>→</span></button><a className="text-link" href="#how">Learn how it works <span>↓</span></a></div><p className="note">Wellness prototype only. It does not diagnose, prescribe, or replace clinical equipment.</p></div><div className="hero-card"><div className="card-top"><span className="live-dot"></span><span>Illustrative patient check-in</span><span className="lock">⌁ Private by design</span></div><div className="reading"><div><small>Latest pulse</small><strong>74 <em>BPM</em></strong><span className="trend">↗ Steady over this check-in</span></div><div className="pulse-ring"><span>♥</span></div></div><div className="mini-chart"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><div className="card-foot"><span>Camera signal: acceptable</span><span>08:42 AM</span></div></div></section>
    <section className="trust"><p>Designed for the moments between appointments</p><div><span>Patient-friendly</span><span>Medication-aware</span><span>Doctor-ready summaries</span></div></section>
    <section id="how" className="section"><div className="section-heading"><p className="eyebrow">THE IDEA</p><h2>From a quick check-in to a useful conversation.</h2><p>Learn how PulseWindow turns subtle camera signals into trends that can be discussed with a healthcare team.</p><a className="text-link section-link" href="/how-it-works">Read how it works <span>→</span></a></div></section>
    <section id="care" className="care-section"><div><p className="eyebrow">BUILT AROUND CARE</p><h2>Useful context, not another number.</h2><p>Explore the medication-aware prompts, trend history and clinician-facing summaries behind the concept.</p><a className="secondary inline-button" href="/for-care-teams">For care teams <span>→</span></a></div><div className="care-list"><div><span>01</span><strong>Medication-aware check-ins</strong><p>Prompts can be set around an existing care plan.</p></div><div><span>02</span><strong>Simple trend history</strong><p>Pulse and experimental breathing estimates sit beside their context.</p></div><div><span>03</span><strong>Exportable summaries</strong><p>A readable report can support professional review.</p></div></div></section>
    <section className="closing"><p className="eyebrow">A RESEARCH-LED CONCEPT</p><h2>Better remote conversations start with better context.</h2><p>PulseWindow is being developed with pharmacists, patients, and healthcare collaborators to explore what a calm, accessible check-in could look like.</p><button className="primary" onClick={() => setDemoOpen(true)}>See the concept <span>→</span></button></section>
    <SiteFooter />
    {demoOpen && <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="PulseWindow camera prototype"><div className="modal demo-modal"><button className="close" onClick={() => setDemoOpen(false)} aria-label="Close">×</button><p className="eyebrow">CAMERA PROTOTYPE</p><h2>Try a live check-in.</h2><p>Allow camera access to see the prototype read a green-channel signal locally in your browser.</p><CameraDemo /><button className="modal-back" onClick={() => setDemoOpen(false)}>Back to overview</button></div></div>}
  </main>;
}
